package ru.popov.shogi.classes.figures

enum class  FigureName {
    PAWN,GOLD,SILVER,KING,BISHOP,LANCE,KNIGHT,ROOK,PROMOTED_SILVER,PROMOTED_BISHOP,PROMOTED_LANCE,PROMOTED_ROOK,TOKIN,PROMOTED_KNIGHT
}